# Site information
site_name: Github for Data Science Workshop
site_author: QAlonso Astroza Tagle
site_description: >-
  A workshop to learn how to use Github for Data Science projects.


# Repository
repo_name: idsudd/github-workshop
repo_url: https://github.com/idsudd/github-workshop


# Configuration
theme:
  name: material
  icon:
    logo: material/book-heart-outline
  palette:
    - scheme: default
      primary: white
  font:
    text: Inter
    code: Source Code Pro
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
    - announce.dismiss
    - content.tabs.link
    - content.footnote.tooltips


# Copyright
copyright: Copyright &copy; 2024 Instituto de Data Science, Facultad de Ingeniería, Universidad del Desarrollo.

# Additional configuration
extra:
  analytics:
    provider: google
    property: G-93GNCVX8RQ
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:alonsoastroza@udd.cl

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - section-index
  - social:
      cards_layout_options:
        color: #173a58
  
nav:
  - Home: index.md
  - Bienvenida:
      - Welcome to the course: welcome.md
  - Contenido:
      - content/index.md
      - Contexto: content/context.md
      - Desafíos: content/challenges.md
      - Cookiecutter: content/cookiecutter.md
      - Git: content/git.md
      - Próximos pasos: content/next-steps.md
  - Material:
    - material/index.md 
  - Instructor:
    - instructor/index.md